batch_size: 512
eval_batch_size: 256
dropout: 0.15
lr: 0.001
num_layers: 7
JK : "none"
task_names:
  - "cora_link"
  - "cora_node"
  - "pubmed_link"
  - "pubmed_node"
  - "arxiv"


d_multiple:
  - 1.5
  - 2
  - 0.5
  - 2.5
  - 0.7


d_min_ratio:
  - 1
  - 1
  - 0.1
  - 2
  - 0.2
