batch_size: 64
eval_batch_size: 128
dropout: 0.15
lr: 0.0001
num_layers: 5
JK : "none"
task_names:
  - "bookhis"
  - "bookchild"
  - "elephoto"
  - "elecomp"
  - "sportsfit"
  - "products"



d_multiple:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1



d_min_ratio:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

