batch_size: 256
eval_batch_size: 256
dropout: 0.15
lr: 0.001
num_layers: 3
JK : "none"
task_names:
  - "citeseer_node_high"
  - "cora_node_high"
  - "arxiv"
  - "arxiv23"


d_multiple:
  - 1
  - 1
  - 1
  - 1


d_min_ratio:
  - 1
  - 1
  - 1
  - 1
