batch_size: 512
eval_batch_size: 256
dropout: 0.15
lr: 0.001
num_layers: 7
num_epochs: 35
JK : "none"
task_names:
  - "chemblpre"
  - "chempcba"
  - "chemhiv"
  - "tox21"
  - "toxcast"
  - "bace"
  - "bbbp"
  - "muv"

d_multiple:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

d_min_ratio:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1