batch_size: 256
eval_batch_size: 256
dropout: 0.15
lr: 0.001
num_layers: 3
JK : "none"
task_names:
  - "citeseer_node"
  - "cora_node"
  - "pubmed_node"
  - "arxiv"


d_multiple:
  - 2
  - 2
  - 2.5
  - 0.7


d_min_ratio:
  - 1
  - 1
  - 2
  - 0.2
