batch_size: 512
eval_batch_size: 256
dropout: 0.15
lr: 0.001
num_layers: 7
JK : "none"
task_names:
  - "chemblpre"
  - "chempcba"
  - "chemhiv"

d_multiple:
  - 1
  - 2
  - 4

d_min_ratio:
  - 0.2
  - 0.2
  - 2