batch_size: 256
eval_batch_size: 256
dropout: 0.15
lr: 0.001
num_layers: 5
JK : "none"
task_names:
  - "cora_link"
  - "pubmed_link"
  - "citeseer_link"
  - "cora_node"
  - "pubmed_node"
  - "citeseer_node"
  

d_multiple:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1



d_min_ratio:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
