batch_size: 256
eval_batch_size: 256
dropout: 0.15
lr: 0.001
num_layers: 5
JK : "none"
task_names:
  - "bookhis"
  - "bookchild"
  - "elecomp"
  - "elephoto"
  - "sportsfit"
  - "products"
  - "amazonratings"


d_multiple:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1


d_min_ratio:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

