DATASET = {
    'cora': {'name': 'cora', 'level': 'node', 'task_dim': 7, 'metric': 'accuracy'},
    'cora-link': {'name': 'cora-link', 'level': 'link', 'task_dim': 1, 'metric': 'hits@100'},
    'citeseer': {'name': 'citeseer', 'level': 'node', 'task_dim': 6, 'metric': 'accuracy'},
    'citeseer-link': {'name': 'citeseer-link', 'level': 'link', 'task_dim': 1, 'metric': 'hits@100'},
    'pubmed': {'name': 'pubmed', 'level': 'node', 'task_dim': 3, 'metric': 'accuracy'},
    'pubmed-link': {'name': 'pubmed-link', 'level': 'link', 'task_dim': 1, 'metric': 'hits@100'},
    'arxiv': {'name': 'arxiv', 'level': 'node', 'task_dim': 40, 'metric': 'accuracy'},
    'arxiv23': {'name': 'arxiv23', 'level': 'node', 'task_dim': 40, 'metric': 'accuracy'},
    # 'arxiv23-link': {'name': 'arxiv23-link', 'level': 'link'},
    'bookchild': {'name': 'bookchild', 'level': 'node', 'task_dim': 24, 'metric': 'accuracy'},
    'bookhis': {'name': 'bookhis', 'level': 'node', 'task_dim': 12, 'metric': 'accuracy'},
    'elecomp': {'name': 'elecomp', 'level': 'node', 'task_dim': 10, 'metric': 'f1'},
    'elephoto': {'name': 'elephoto', 'level': 'node', 'task_dim': 12, 'metric': 'f1'},
    'sportsfit': {'name': 'sportsfit', 'level': 'node', 'task_dim': 13, 'metric': 'f1'},
    'products': {'name': 'products', 'level': 'node', 'task_dim': 39, 'metric': 'accuracy'},
    'wikics': {'name': 'wikics', 'level': 'node', 'task_dim': 10, 'metric': 'accuracy'},
    'wikics-link': {'name': 'wikics-link', 'level': 'link', 'task_dim': 1, 'metric': 'hits@100'},
    'chempcba': {'name': 'chempcba', 'level': 'graph', 'task_dim': 128, 'metric': 'apr'},
    'chemhiv': {'name': 'chemhiv', 'level': 'graph', 'task_dim': 1, 'metric': 'auc'},
    'tox21': {'name': 'tox21', 'level': 'graph', 'task_dim': 12, 'metric': 'auc'},
    'bace': {'name': 'bace', 'level': 'graph', 'task_dim': 1, 'metric': 'auc'},
    'bbbp': {'name': 'bbbp', 'level': 'graph', 'task_dim': 1, 'metric': 'auc'},
    'muv': {'name': 'muv', 'level': 'graph', 'task_dim': 17, 'metric': 'auc'},
    'toxcast': {'name': 'toxcast', 'level': 'graph', 'task_dim': 588, 'metric': 'auc'},
}