# @package _global_
llm:
  _file_: <LLM-${.name}>
  name: Bedrock
  openai_name: anthropic.claude-3-5-sonnet-20240620-v1:0
  temperature: 0 # Fix
  _target_: gtext.llm.bedrockm.Bedrock
  _type: Bedrock
  hidden_dim: 9999
  sleep_time: 1