E2E-node: &E2E-node
  task_level: e2e_node
  preprocess: null
  construct: ConstructNodeCls
  args:
    walk_length: null
    single_prompt_edge: False
    max_nodes_per_hop: 100
  eval_metric: acc
  eval_func: classification_func
  eval_mode: max

arxiv: &arxiv
  <<: *E2E-node
  dataset_name: arxiv
  dataset_splitter: OGB_Splitter
  process_label_func: process_pth_label
  num_classes: 40

arxiv23: &arxiv23
  <<: *E2E-node
  dataset_name: arxiv23
  dataset_splitter: OGB_Splitter
  process_label_func: process_pth_label
  num_classes: 40

bookhis: &bookhis
  <<: *E2E-node
  dataset_name: bookhis
  dataset_splitter: OfficialSplitter
  process_label_func: process_pth_label
  num_classes: 12

bookchild: &bookchild
  <<: *E2E-node
  dataset_name: bookchild
  dataset_splitter: OfficialSplitter
  process_label_func: process_pth_label
  num_classes: 24

elecomp: &elecomp
  <<: *E2E-node
  dataset_name: elecomp
  dataset_splitter: OfficialSplitter
  process_label_func: process_pth_label
  num_classes: 10

elephoto: &elephoto
  <<: *E2E-node
  dataset_name: elephoto
  dataset_splitter: OfficialSplitter
  process_label_func: process_pth_label
  num_classes: 12

sportsfit: &sportsfit
  <<: *E2E-node
  dataset_name: sportsfit
  dataset_splitter: OfficialSplitter
  process_label_func: process_pth_label
  num_classes: 13

amazonratings: &amazonratings
  <<: *E2E-node
  dataset_name: amazonratings
  dataset_splitter: OfficialSplitter
  process_label_func: process_pth_label
  num_classes: 5

products: &products
  <<: *E2E-node
  dataset_name: products
  dataset_splitter: OfficialSplitter
  process_label_func: process_pth_label
  num_classes: 39

logic_arxiv: &logic_arxiv
  <<: *arxiv
  task_level: logic_e2e
  process_label_func: process_logic_label
  eval_metric: auc
  eval_func: flat_auc

cora_node: &cora_node
  <<: *E2E-node
  dataset_name: cora
  dataset_splitter: CiteSplitter
  process_label_func: process_int_label
  num_classes: 7

citeseer_node: &citeseer_node
  <<: *E2E-node
  dataset_name: citeseer
  dataset_splitter: OfficialSplitter
  process_label_func: process_int_label
  num_classes: 6

logic_cora: &logic_cora
  <<: *cora_node
  task_level: logic_e2e
  process_label_func: process_logic_label
  eval_metric: auc
  eval_func: flat_auc

pubmed_node: &pubmed_node
  <<: *E2E-node
  dataset_name: pubmed
  dataset_splitter: CiteSplitter
  process_label_func: process_int_label
  num_classes: 3

wikics: &wikics
  <<: *E2E-node
  dataset_name: wikics
  dataset_splitter: WikiSplitter
  process_label_func: process_pth_label
  num_classes: 10

link-eval-args: &link-eval-args
  remove_edge: False
  walk_length: null
  max_nodes_per_hop: 100

E2E-link: &E2E-link
  task_level: e2e_link
  args:
    remove_edge: True
    walk_length: null
    max_nodes_per_hop: 100

E2E-link-cite: &E2E-link-cite
  <<: *E2E-link
  preprocess: LinkConstructGraph
  construct: ConstructLinkCls
  dataset_splitter: CiteLinkSplitter
  process_label_func: process_int_label
  eval_metric: hits@k
  eval_func: binary_auc_func
  num_classes: 2
  eval_mode: max

cora_link: &cora_link
  <<: *E2E-link-cite
  dataset_name: cora

cora_link_eval:
  <<: *cora_link
  args:
    <<: *link-eval-args

citationv8: &citationv8
  <<: *E2E-link-cite
  dataset_splitter: OfficialLinkSplitter
  dataset_name: citationv8

citationv8_eval: &citationv8_eval
  <<: *citationv8
  args:
    <<: *link-eval-args
  
goodreads: &goodreads
  <<: *E2E-link-cite
  dataset_name: goodreads

goodreads_eval: &goodreads_eval
  <<: *goodreads
  args:
    <<: *link-eval-args

pubmed_link: &pubmed_link
  <<: *E2E-link-cite
  dataset_name: pubmed

pubmed_link_eval:
  <<: *pubmed_link
  args:
    <<: *link-eval-args

citeseer_link: &citeseer_link
  <<: *E2E-link-cite
  dataset_name: citeseer

citeseer_link_eval:
  <<: *citeseer_link
  args:
    <<: *link-eval-args

wikics_link: &wikics_link
  <<: *E2E-link-cite
  dataset_name: wikics

wikics_link_eval:
  <<: *wikics_link
  args:
    <<: *link-eval-args

E2E-link-KG: &E2E-link-KG
  <<: *E2E-link
  dataset_splitter: KGSplitter
  preprocess: KGConstructEdgeList
  construct: ConstructKG
  process_label_func: process_int_label
  eval_metric: acc
  eval_func: classification_func
  eval_mode: max

WN18RR: &WN18RR
  <<: *E2E-link-KG
  dataset_name: WN18RR
  num_classes: 11

WN18RR_eval: &WN18RR_eval
  <<: *WN18RR
  args:
    <<: *link-eval-args

FB15K237: &FB15K237
  <<: *E2E-link-KG
  dataset_name: FB15K237
  num_classes: 237

FB15K237_eval: &FB15K237_eval
  <<: *FB15K237
  args:
    <<: *link-eval-args

E2E-graph: &E2E-graph
  task_level: e2e_graph
  dataset_splitter: MolSplitter
  preprocess: null
  construct: ConstructMolCls
  args:
    walk_length: null
  eval_mode: max

chemblpre: &chemblpre
  <<: *E2E-graph
  dataset_name: chemblpre
  process_label_func: process_positive_negative_multi_label
  eval_metric: apr
  eval_func: binary_apr_func
  num_classes: 1295

chempcba: &chempcba
  <<: *E2E-graph
  dataset_name: chempcba
  process_label_func: process_positive_negative_multi_label
  eval_metric: apr
  eval_func: binary_apr_func
  num_classes: 128

chempcba_eval: &chempcba_eval
  <<: *chempcba
  process_label_func: process_label_positive_only

chemhiv: &chemhiv
  <<: *E2E-graph
  dataset_name: chemhiv
  process_label_func: process_reverse_binary_label
  eval_metric: auc
  eval_func: binary_auc_func
  num_classes: 2
  
tox21: &tox21
  <<: *E2E-graph
  dataset_name: tox21
  process_label_func: process_positive_negative_multi_label
  eval_metric: aucmulti
  eval_func: binary_auc_multi_func
  num_classes: 12

tox21_eval: &tox21_eval
  <<: *tox21
  process_label_func: process_label_positive_only

muv: &muv
  <<: *E2E-graph
  dataset_name: muv
  process_label_func: process_positive_negative_multi_label
  eval_metric: aucmulti
  eval_func: binary_auc_multi_func
  num_classes: 17

muv_eval: &muv_eval
  <<: *muv
  process_label_func: process_label_positive_only

toxcast: &toxcast
  <<: *E2E-graph
  dataset_name: toxcast
  process_label_func: process_positive_negative_multi_label
  eval_metric: aucmulti
  eval_func: binary_auc_multi_func
  num_classes: 588

toxcast_eval: &toxcast_eval
  <<: *toxcast
  process_label_func: process_label_positive_only

bace: &bace
  <<: *E2E-graph
  dataset_name: bace
  process_label_func: process_reverse_binary_label
  eval_metric: auc
  eval_func: binary_auc_func
  num_classes: 2

bbbp: &bbbp
  <<: *E2E-graph
  dataset_name: bbbp
  process_label_func: process_reverse_binary_label
  eval_metric: auc
  eval_func: binary_auc_func
  num_classes: 2



LR-node: &LR-node
  task_level: lr_node
  construct: ConstructFSTask
  args:
    walk_length: null
    single_prompt_edge: True
  eval_metric: acc
  eval_func: classification_func
  eval_mode: max

arxiv_fs: &arxiv_fs
  <<: *LR-node
  dataset_name: arxiv
  dataset_splitter: ArxivFSSplitter
  process_label_func: process_pth_label
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 5
    min_k_shot: 0
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 5

arxiv_fs_51:
  <<: *arxiv_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 1
    base_construct: ConstructNodeCls
    no_class_node: True


arxiv_fs_53:
  <<: *arxiv_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 3
    base_construct: ConstructNodeCls
    no_class_node: True

arxiv_fs_55:
  <<: *arxiv_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 5
    base_construct: ConstructNodeCls
    no_class_node: True

cora_fs: &cora_fs
  <<: *LR-node
  dataset_name: cora
  dataset_splitter: CiteFSSplitter
  process_label_func: process_int_label
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 2
    k_shot: 1
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 2

cora_fs_21:
  <<: *cora_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 2
    k_shot: 1
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 2


cora_fs_23:
  <<: *cora_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 2
    k_shot: 3
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 2


cora_fs_25:
  <<: *cora_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 2
    k_shot: 5
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 2


cora_fs_71:
  <<: *cora_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 7
    k_shot: 1
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 7


cora_fs_73:
  <<: *cora_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 7
    k_shot: 3
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 7


cora_fs_75:
  <<: *cora_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 7
    k_shot: 5
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 7

cora_fs_70:
  <<: *cora_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 7
    k_shot: 0
    base_construct: ConstructNodeCls
    no_class_node: True
  num_classes: 7

LR-link: &LR-link
  task_level: lr_link
  construct: ConstructFSTask
  preprocess: KGConstructEdgeList
  args:
    walk_length: null
    single_prompt_edge: True
  eval_metric: acc
  eval_func: classification_func
  eval_mode: max

FB15K237_fs: &FB15K237_fs
  <<: *LR-link
  dataset_name: FB15K237
  dataset_splitter: KGFSTrainSplitter
  process_label_func: process_int_label
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 20
    k_shot: 5
    min_k_shot: 1
    min_n_way: 10
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 20

FB15K237_fs_101:
  <<: *FB15K237_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 10
    k_shot: 1
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 10


FB15K237_fs_103:
  <<: *FB15K237_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 10
    k_shot: 3
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 10

FB15K237_fs_105:
  <<: *FB15K237_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 10
    k_shot: 5
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 10


FB15K237_fs_201:
  <<: *FB15K237_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 20
    k_shot: 1
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 20


FB15K237_fs_203:
  <<: *FB15K237_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 20
    k_shot: 3
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 20

FB15K237_fs_205:
  <<: *FB15K237_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 20
    k_shot: 5
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 20


WN18RR_fs: &WN18RR_fs
  <<: *LR-link
  dataset_name: WN18RR
  dataset_splitter: KGFSSplitter
  process_label_func: process_int_label
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 1
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: False
  num_classes: 5


WN18RR_fs_51:
  <<: *WN18RR_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 1
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: False
  num_classes: 5

WN18RR_fs_53:
  <<: *WN18RR_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 3
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: False
  num_classes: 5


WN18RR_fs_55:
  <<: *WN18RR_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 5
    k_shot: 5
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: False
  num_classes: 5
