E2E-node: &E2E-node
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

pretrain: &pretrain
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: valid
      dataset: cora_node
    - stage: test
      split_name: test
      dataset: cora_node



arxiv: &arxiv
  <<: *E2E-node
  dataset: arxiv

arxiv23: &arxiv23
  <<: *E2E-node
  dataset: arxiv23

bookhis: &bookhis
  <<: *E2E-node
  dataset: bookhis

bookchild: &bookchild
  <<: *E2E-node
  dataset: bookchild

elecomp: &elecomp
  <<: *E2E-node
  dataset: elecomp

elephoto: &elephoto
  <<: *E2E-node
  dataset: elephoto

sportsfit: &sportsfit
  <<: *E2E-node
  dataset: sportsfit
  
cora_node: &cora_node
  <<: *E2E-node
  dataset: cora_node

pubmed_node: &pubmed_node
  <<: *E2E-node
  dataset: pubmed_node

citeseer_node: &citeseer_node
  <<: *E2E-node
  dataset: citeseer_node

cora_node_high: &cora_node_high
  <<: *E2E-node
  dataset: cora_node_high

citeseer_node_high: &citeseer_node_high
  <<: *E2E-node
  dataset: citeseer_node_high

pubmed_node_high: &pubmed_node_high
  <<: *E2E-node
  dataset: pubmed_node_high

dblp_node: &dblp_node
  <<: *E2E-node
  dataset: dblp_node

dblp_node_high: &dblp_node_high
  <<: *E2E-node
  dataset: dblp_node_high

wikics: &wikics
  <<: *E2E-node
  dataset: wikics

products: &products
  <<: *E2E-node
  dataset: products

amazonratings: &amazonratings
  <<: *E2E-node
  dataset: amazonratings

tolokers: &tolokers
  <<: *E2E-node
  dataset: tolokers

arxivyear: &arxivyear
  <<: *E2E-node
  dataset: arxivyear

bookhis20: &bookhis20
  <<: *E2E-node
  dataset: bookhis20

bookchild20: &bookchild20
  <<: *E2E-node
  dataset: bookchild20

elecomp20: &elecomp20
  <<: *E2E-node
  dataset: elecomp20

elephoto20: &elephoto20
  <<: *E2E-node
  dataset: elephoto20

sportsfit20: &sportsfit20
  <<: *E2E-node
  dataset: sportsfit20

products20: &products20
  <<: *E2E-node
  dataset: products20

arxiv20: &arxiv20
  <<: *E2E-node
  dataset: arxiv20

arxiv2320: &arxiv2320
  <<: *E2E-node
  dataset: arxiv2320

mag240m: &mag240m
  <<: *E2E-node
  dataset: mag240m
  eval_set_constructs:
    - stage: train
      split_name: train


arxivall: &arxivall
  <<: *pretrain
  dataset: arxivall

productsall: &productsall
  <<: *pretrain
  dataset: productsall

sportsfitall: &sportsfitall
  <<: *pretrain
  dataset: sportsfitall

logic_arxiv:
  <<: *E2E-node
  dataset: logic_arxiv
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: logic_arxiv
    - stage: valid
      split_name: valid
      dataset: logic_cora
    - stage: test
      split_name: test
      dataset: logic_cora
    - stage: test
      split_name: train
      dataset: logic_cora

logic_cora:
  <<: *E2E-node
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: cora_node
    - stage: valid
      split_name: valid
      dataset: cora_node
    - stage: valid
      split_name: valid
      dataset: logic_cora
    - stage: test
      split_name: test
      dataset: logic_cora
    - stage: test
      split_name: train
      dataset: logic_cora

E2E-link: &E2E-link
  eval_pool_mode: mean
  task_level: e2e_link

# cora_link: &cora_link
#   <<: *E2E-link
#   eval_set_constructs:
#     - stage: train
#       split_name: train
#       dataset: cora_link
#     - stage: valid
#       split_name: valid
#       dataset: cora_link_eval
#     - stage: valid
#       split_name: valid
#       dataset: cora_node
#     - stage: test
#       split_name: test
#       dataset: cora_link_eval
#     - stage: test
#       split_name: train
#       dataset: cora_link

cora_link: &cora_link
  <<: *E2E-link
  dataset: cora_link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: cora_link
    - stage: valid
      split_name: valid
      dataset: cora_link_eval
    - stage: test
      split_name: test
      dataset: cora_link_eval
    - stage: test
      split_name: train
      dataset: cora_link

pubmed_link: &pubmed_link
  <<: *E2E-link
  dataset: pubmed_link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: pubmed_link
    - stage: valid
      split_name: valid
      dataset: pubmed_link_eval
    - stage: test
      split_name: test
      dataset: pubmed_link_eval
    - stage: test
      split_name: train
      dataset: pubmed_link

pubmed_link_zero_shot: &pubmed_link_zero_shot
  <<: *E2E-link
  dataset: pubmed_link
  eval_set_constructs:
    - stage: valid
      split_name: valid
      dataset: pubmed_link_eval
    - stage: test
      split_name: test
      dataset: pubmed_link_eval

citeseer_link: &citeseer_link
  <<: *E2E-link
  dataset: citeseer_link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: citeseer_link
    - stage: valid
      split_name: valid
      dataset: citeseer_link_eval
    - stage: test
      split_name: test
      dataset: citeseer_link_eval
    - stage: test
      split_name: train
      dataset: citeseer_link

dblp_link: &dblp_link
  <<: *E2E-link
  dataset: dblp_link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: dblp_link
    - stage: valid
      split_name: valid
      dataset: dblp_link_eval
    - stage: test
      split_name: test
      dataset: dblp_link_eval
    - stage: test
      split_name: train
      dataset: dblp_link



FB15K237: &FB15K237
  <<: *E2E-link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: FB15K237
    - stage: valid
      split_name: valid
      dataset: FB15K237_eval
    - stage: test
      split_name: test
      dataset: FB15K237_eval
    - stage: test
      split_name: train
      dataset: FB15K237

WN18RR: &WN18RR
  <<: *E2E-link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: WN18RR
    - stage: valid
      split_name: valid
      dataset: WN18RR_eval
    - stage: test
      split_name: test
      dataset: WN18RR_eval
    - stage: test
      split_name: train
      dataset: WN18RR

E2E-graph: &E2E-graph
  task_level: e2e_graph
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

chemblpre: &chemblpre
  <<: *E2E-graph
  dataset: chemblpre
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: chemblpre
    - stage: valid
      split_name: valid
      dataset: chemhiv 
    - stage: test
      split_name: test
      dataset: chemhiv
    - stage: test
      split_name: test
      dataset: cora_node 
    - stage: test
      split_name: test
      dataset: bookhis
    - stage: test
      split_name: test
      dataset: pubmed_link
    - stage: test
      split_name: test
      dataset: amazonratings
    # - stage: valid
    #   split_name: valid
    #   dataset: chempcba_eval
    # - stage: valid
    #   split_name: valid
    #   dataset: chemhiv
    # - stage: test
    #   split_name: test
    #   dataset: chemhiv

chempcba: &chempcba
  <<: *E2E-graph
  dataset: chempcba
  train: chempcba
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: chempcba
    - stage: valid
      split_name: valid
      dataset: chempcba_eval
    - stage: test
      split_name: test
      dataset: chempcba_eval
    - stage: test
      split_name: train
      dataset: chempcba_eval

chemhiv: &chemhiv
  <<: *E2E-graph
  dataset: chemhiv

tox21: &tox21
  <<: *E2E-graph
  train: tox21
  dataset: tox21
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: tox21
    - stage: valid
      split_name: valid
      dataset: tox21_eval
    - stage: test
      split_name: test
      dataset: tox21_eval
    - stage: test
      split_name: train
      dataset: tox21_eval



muv: &muv
  <<: *E2E-graph
  train: muv
  dataset: muv
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: muv
    - stage: valid
      split_name: valid
      dataset: muv_eval
    - stage: test
      split_name: test
      dataset: muv_eval
    - stage: test
      split_name: train
      dataset: muv_eval


toxcast: &toxcast
  <<: *E2E-graph
  train: toxcast
  dataset: toxcast
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: toxcast
    - stage: valid
      split_name: valid
      dataset: toxcast_eval
    - stage: test
      split_name: test
      dataset: toxcast_eval
    - stage: test
      split_name: train
      dataset: toxcast_eval

bace: &bace
  <<: *E2E-graph
  dataset: bace

bbbp: &bbbp
  <<: *E2E-graph
  dataset: bbbp




LR-node: &LR-node
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

arxiv_fs: &arxiv_fs
  <<: *LR-node
  dataset: arxiv_fs
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: arxiv_fs
    - stage: valid
      split_name: valid
      dataset: cora_fs_73
    - stage: valid
      split_name: valid
      dataset: cora_fs_75
    - stage: test
      split_name: test
      dataset: arxiv_fs_51
    - stage: test
      split_name: test
      dataset: arxiv_fs_53
    - stage: test
      split_name: test
      dataset: arxiv_fs_55
    - stage: test
      split_name: test
      dataset: cora_fs_21
    - stage: test
      split_name: test
      dataset: cora_fs_23
    - stage: test
      split_name: test
      dataset: cora_fs_25
    - stage: test
      split_name: test
      dataset: cora_fs_71
    - stage: test
      split_name: test
      dataset: cora_fs_73
    - stage: test
      split_name: test
      dataset: cora_fs_75

LR-link: &LR-link
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

FB15K237_fs: &FB15K237_fs
  <<: *LR-link
  dataset: FB15K237_fs
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: FB15K237_fs
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_101
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_103
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_105
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_201
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_203
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_205
    - stage: valid
      split_name: valid
      dataset: WN18RR_fs_51
    - stage: valid
      split_name: valid
      dataset: WN18RR_fs_53
    - stage: valid
      split_name: valid
      dataset: WN18RR_fs_55
    - stage: test
      split_name: test
      dataset: FB15K237_fs_101
    - stage: test
      split_name: test
      dataset: FB15K237_fs_103
    - stage: test
      split_name: test
      dataset: FB15K237_fs_105
    - stage: test
      split_name: test
      dataset: FB15K237_fs_201
    - stage: test
      split_name: test
      dataset: FB15K237_fs_203
    - stage: test
      split_name: test
      dataset: FB15K237_fs_205
    - stage: test
      split_name: test
      dataset: WN18RR_fs_51
    - stage: test
      split_name: test
      dataset: WN18RR_fs_53
    - stage: test
      split_name: test
      dataset: WN18RR_fs_55


arxivcorafs: &arxivcorafs
  <<: *LR-node
  dataset: arxiv
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: arxiv
    - stage: valid
      split_name: valid
      dataset: cora_fs_70
    - stage: test
      split_name: test
      dataset: cora_fs_70

fstest: &fstest
  <<: *LR-node
  dataset: arxiv
  eval_set_constructs:
    - stage: valid
      split_name: valid
      dataset: cora_fs_70
    - stage: test
      split_name: test
      dataset: cora_fs_70

zero_shot_orig: &zero_shot_orig
  <<: *LR-node
  dataset: arxiv
  eval_set_constructs:
    - stage: valid
      split_name: valid
      dataset: cora_node
    - stage: test
      split_name: test
      dataset: cora_node
    - stage: test
      split_name: test
      dataset: bookhis
    - stage: test
      split_name: test
      dataset: arxiv23
    - stage: test
      split_name: test
      dataset: pubmed_link
    - stage: test
      split_name: test
      dataset: amazonratings
    - stage: test
      split_name: test
      dataset: chemhiv

low_cora_orig: &low_cora_orig
  <<: *E2E-node
  dataset: cora
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: cora_node_low
    - stage: valid
      split_name: valid
      dataset: cora_node_low
    - stage: test
      split_name: test
      dataset: cora_node_low

bookhis_orig: &bookhis_orig
  <<: *E2E-node
  dataset: bookhis
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: bookhis_low
    - stage: valid
      split_name: valid
      dataset: bookhis_low
    - stage: test
      split_name: test
      dataset: bookhis_low

arxiv23_orig: &arxiv23_orig
  <<: *E2E-node
  dataset: arxiv23
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: arxiv23_low
    - stage: valid
      split_name: valid
      dataset: arxiv23_low
    - stage: test
      split_name: test
      dataset: arxiv23_low

chemhiv_orig: &chemhiv_orig
  <<: *E2E-node
  dataset: chemhiv
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: chemhiv_low
    - stage: valid
      split_name: valid
      dataset: chemhiv_low
    - stage: test
      split_name: test
      dataset: chemhiv_low

amazonratings_orig: &amazonratings_orig
  <<: *E2E-node
  dataset: amazonratings
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: amazonratings_low
    - stage: valid
      split_name: valid
      dataset: amazonratings_low
    - stage: test
      split_name: test
      dataset: amazonratings_low


low_cora_test: &low_cora_test
  <<: *LR-node
  dataset: cora
  eval_set_constructs:
    - stage: valid
      split_name: valid
      dataset: cora_lr
    - stage: test
      split_name: test
      dataset: cora_lr


pre_train_fs: &pre_train_fs
  <<: *LR-node
  dataset: arxiv_fs
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: arxiv_fs
    - stage: train
      split_name: train
      dataset: products_fs
    - stage: train
      split_name: train
      dataset: sportsfit_fs
    - stage: valid
      split_name: valid
      dataset: cora_fs_70
    - stage: test
      split_name: test
      dataset: cora_fs_70
    - stage: test
      split_name: test
      dataset: cora_fs_73
    - stage: test
      split_name: test 
      dataset: bookhis_fs
    - stage: test
      split_name: test
      dataset: bookhis_fs_120
    - stage: test
      split_name: test
      dataset: amazonratings_fs
    - stage: test
      split_name: test
      dataset: amazonratings_fs_50

LR-graph: &LR-graph
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train

mol_fs: &mol_fs
  <<: *LR-graph
  dataset: chemhive_fs
  eval_set_constructs:
    - stage: valid
      split_name: valid
      dataset: chemhiv_fs_20
    - stage: test
      split_name: test
      dataset: chemhiv_fs_20
    - stage: test
      split_name: test
      dataset: chemhiv_fs_23

